backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/resources/main"
public_folder: "resources/main"

collections:
  # Fare stops
  - name: "stops_data"
    label: "Jeepney Information"
    folder: "source/container/command/calculate/stops_data"
    create: true # Prevent users from creating new documents in this collection
    slug: "{{stop_number}}-{{stop_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - label: "Jeepney Stop"
        name: "stop_name"
        widget: "string"

      - label: "Distance from Main Terminal (KM)"
        name: "distance_from_terminal"
        widget: "string"

      - label: "Stop Number (Index)"
        name: "stop_number"
        widget: "string"

      - label: "Identifier"
        name: "tags"
        widget: "string"

  # More
  - name: "index"
    label: "Homepage"
    folder: "source/container/command/index"
    create: false # Prevent users from creating new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{product_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - label: "Homepage"
        name: "name"
        widget: "string"

      # Others
      - label: "Website Logo"
        name: "website_logo"
        widget: "image"

      # First Article
      - label: "First Article Title - Homepage"
        name: "first_article_name"
        widget: "string"

      - label: "First Article Link - Homepage"
        name: "first_article_link"
        widget: "string"

      - label: "First Article Description - Homepage"
        name: "first_article_description"
        widget: "markdown"

      - label: "First Article Image Alternative - Homepage"
        name: "first_article_image_alternative"
        widget: "string"

      - label: "First Article Image - Homepage"
        name: "first_article_image"
        widget: "image"

      # Second Article
      - label: "Second Article Title - Homepage"
        name: "second_article_name"
        widget: "string"

      - label: "Second Article Link - Homepage"
        name: "second_article_link"
        widget: "string"

      - label: "Second Article Description - Homepage"
        name: "second_article_description"
        widget: "markdown"

      - label: "Second Article Image Alternative - Homepage"
        name: "second_article_image_alternative"
        widget: "string"

      - label: "Second Article Image - Homepage"
        name: "second_article_image"
        widget: "image"

  # More
  - name: "more"
    label: "More"
    folder: "source/container/command/more"
    create: false # Prevent users from creating new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{product_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      # First Article
      - label: "More"
        name: "name"
        widget: "string"

      - label: "First Article Title - About"
        name: "first_article_name"
        widget: "string"

      - label: "First Article Description - About"
        name: "first_article_description"
        widget: "markdown"

      # Second Article
      - label: "Second Article Title - About"
        name: "second_article_name"
        widget: "string"

      - label: "Technology List"
        name: "techA"
        widget: "string"

      - label: "Technology List"
        name: "techB"
        widget: "string"

      - label: "Technology List"
        name: "techC"
        widget: "string"

      - label: "Technology List"
        name: "techD"
        widget: "string"

      - label: "Technology List"
        name: "techE"
        widget: "string"

      - label: "Technology List"
        name: "techF"
        widget: "string"

      - label: "Technology List"
        name: "techG"
        widget: "string"

      - label: "Technology List"
        name: "techH"
        widget: "string"

      - label: "Technology List"
        name: "techI"
        widget: "string"

  # About
  - name: "about"
    label: "About"
    folder: "source/container/command/about"
    create: false # Prevent users from creating new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{product_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      # First Article
      - label: "First Article Title - About"
        name: "first_article_name"
        widget: "string"

      - label: "First Article Description - About"
        name: "first_article_description"
        widget: "markdown"

      # Second Article (Group Members)
      - label: "Group Member"
        name: "memberA"
        widget: "string"

      - label: "Group Member"
        name: "memberB"
        widget: "string"

      - label: "Group Member"
        name: "memberC"
        widget: "string"

      - label: "Group Member"
        name: "memberD"
        widget: "string"

      - label: "Group Member"
        name: "memberE"
        widget: "string"

      - label: "Group Member"
        name: "memberF"
        widget: "string"

      # Third Article
      - label: "Third Article Title - About"
        name: "third_article_name"
        widget: "string"

      - label: "Third Article Description - About"
        name: "third_article_description"
        widget: "markdown"

      - label: "Email Address"
        name: "email_address"
        widget: "string"

      - label: "Github"
        name: "github_page_name"
        widget: "string"

      - label: "Github Link"
        name: "github_page_link"
        widget: "string"
